export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SHIPS_SUCCESS = 'LOAD_SHIPS_SUCCESS';
export const CREATE_SHIP_SUCCESS = 'CREATE_SHIP_SUCCESS';
export const UPDATE_SHIP_SUCCESS = 'UPDATE_SHIP_SUCCESS';

export const LOAD_SHIP_BLACKLIST_FILTERS_SUCCESS = 'LOAD_SHIP_BLACKLIST_FILTERS_SUCCESS';
export const ADD_SHIP_BLACKLIST_FILTER = 'ADD_SHIP_BLACKLIST_FILTER';
export const REMOVE_SHIP_BLACKLIST_FILTER = 'REMOVE_SHIP_BLACKLIST_FILTER';


export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
